# config/services.yaml
parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
    recipes_directory: '%kernel.project_dir%/public/uploads/recipes'
    app.mail.from_address: '%env(APP_EMAIL_FROM_ADDRESS)%'
    app.mail.from_name: '%env(APP_EMAIL_FROM_NAME)%'
    app.contact.to_address: '%env(APP_CONTACT_TO_ADDRESS)%'
    app.notification_to: 'destinataire@domaine.ext'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Toutes les classes de src/ en services (sauf exclusions)
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #  Contrôleurs tagués (sinon “controller is private / too few arguments”)
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # ➜ Service personnalisé avec arguments
    App\Service\Notification:
        arguments:
            $fromAddress: '%app.mail.from_address%'
            $fromName: '%app.mail.from_name%'
